### ISSUE TITLE
Change the Facebook link on the homepage footer

### ISSUE THREAD

**Issue by Bangledorf** [worthingtonjg/pendantbooks#11]
Let's change the link from the Facebook link in the footer on the homepage to Pendant's Facebook page: https://www.facebook.com/Pendant-Publishing-112500482200442 If it's not possible to have a separate footer link on the different pages, then let's just use the Pendant page on all of them, otherwise, the James Batchelor page is fine for all the other pages except for the "About" page, which should also link to Pendant's page.

**Comment by worthingtonjg** [comment]
Without a lot of work, it isn't easy to do a different facebook link in the footer depending on the page, so they are all using the Pendant Publishing facebook page
