### ISSUE TITLE
Acknowledgement

### ISSUE THREAD

**Issue by Bangledorf** [worthingtonjg/pendantbooks#13]
Would you like an acknowledgment down in the footer as a means of drumming up business or adding to your resume? See my attached screenshot for an example of the kind of thing I see others do. It says "site by <name>" and has a redirect to wherever you would like. 

I'm totally fine with it, if you want to do something like that.
![Screen Shot 2021-07-13 at 12 25 57 PM](https://user-images.githubusercontent.com/86748202/125505654-efc4db65-316c-44ca-b122-9e5fdee55262.png)

**Comment by worthingtonjg** [comment]
No acknowledgement needed.
