### ISSUE TITLE
authors branch

### ISSUE THREAD

**Issue by Bangledorf** [worthingtonjg/pendantbooks#15]
Add a pendantbooks.com/authors/ branch where my page and my brother's (which I have just added) can be hosted. Neither the authors name nor "Authors" should appear in the top menu.

The intent is that I can add as many author pages as I want in the future without disrupting anything.

**Comment by worthingtonjg** [comment]
I've added these pages, under /authors/ and hidden them from the topmenu with topmenu: false

https://worthingtonjg.github.io/pendantbooks/authors/james_batchelor/
https://worthingtonjg.github.io/pendantbooks/authors/jared_batchelor/
