### ISSUE TITLE
Display hashtag in blog title

### ISSUE THREAD

**Issue by Bangledorf** [worthingtonjg/pendantbooks#16]
Is there a way to display a "#" in a blog title. The blog post "MyWritingProcess" refers to a hashtag with contributions from hundreds of authors around the world, but I cannot get it to show in the title. It shows fine in the body of the blog post.

**Comment by worthingtonjg** [comment]
So, looks like this is a limitation of Jekyll, however, I was able to get around it by adding a special "hashtag" parameter in the frontmatter.  If you set hashtag: true, on a post, it will put a hashtag in the front of the title like you want.
