### ISSUE TITLE
Relative Page Links

### ISSUE THREAD

**Issue by Bangledorf** [worthingtonjg/pendantbooks#17]
How do I insert links to other pages on this same site? e.g. when I reference another of my blog posts, how can I just create a link directly to it?

Since this site isn't currently sitting at pendantbooks.com, I can't use direct links, but is there a way I can put in relative links to other site pages that will not break when we move the site live?

**Comment by worthingtonjg** [comment]
To do this, you can use the syntax {{site.baseurl}}, for example, I am linking to images in the image folder this way.  

<img src="{{site.baseurl}}/images/jared_batchelor.jpg" class="img-fluid">
