### ISSUE TITLE
Shop Page

### ISSUE THREAD

**Issue by Bangledorf** [worthingtonjg/pendantbooks#19]
The shop page should have all the books and their fully expanded descriptions and price list listed in order from most recent to oldest, much like the home page but without the blog posts and other items. See http://www.pendantbooks.com/shop/ as an example. These pages redirect to individual pages, but if we just expand them beside the larger images we are using on this site, I don't think there is any reason to do that. Can we replace the individual book page and have it jump from the home page to the correct book on the shop page (if that's possible), and thereby give them a preview of the entire catalogue of books available to them all in one place.

**Comment by worthingtonjg** [comment]
Take a look at the shop page, and tell me if this is what you had in mind?
