### ISSUE TITLE
Links on Blog page don't redirect

### ISSUE THREAD

**Issue by Bangledorf** [worthingtonjg/pendantbooks#20]
I'm not sure if there is anything to be done about this, but on the blog page the questions in the "Why did I re-edit the Knights Dawning post" show as links, but when you click on them nothing happens. Is there a way to make them not appear as links on the top page or to have them jump directly into the post?

FYI: the links work fine within the blog post itself.

**Comment by worthingtonjg** [comment]
The only thing I can do on this one, is to move the "more" tag higher, so the questions don't show up directly on the blog page, since those are links within the page, there isn't anything I can do to make them work.
