### ISSUE TITLE
Jump-to links aren't working in blog post

### ISSUE THREAD

**Issue by Bangledorf** [worthingtonjg/pendantbooks#3]
I'm sure this is just a training thing, but I could not figure out how to make the questions in the list jump to the actual answer in my "Why did I (re)edit the knights Dawning blogpost, like they do in a table of contents for example. I left my tags in, even though they are messing up the formatting, just so you could see what I was trying to do.

**Comment by worthingtonjg** [comment]
I had to change the way you were doing it.  You almost had it the right way - check it out so you know how it is done.
